In [2]:
import pickle

# import lib_py.tensorprep_lib_br as tpl

def load_pickle(filename):
    with open(filename, 'rb') as f:
        return pickle.load(f,encoding='latin1')

In [3]:
path = r'data_BR\synth\crossed_legs\test_roll0_xl_f_lay_set1both_500.p'
dat = load_pickle(path)

.p文件具有的keys:
1. markers_xyz_m: 人体模型的3d关节点坐标 (24,3)
2. body_shape: smpl模型的shape参数, 10个
3. mesh_contact: 模型与床的接触图 (27,64)
4. mesh_depth: 模型深度图 (27, 64)
5. root_xyz_shift: 根节点偏移 (1,3)
6. body_height: 身高(m)
7. body_mass: 体重(kg)
8. images: 可能是pressure image (1728*1 = 64*27)
9. joint_angles: smpl模型的pose参数 (24,3)
10. bed_angle_deg: 床角度偏移？ 1位float

In [4]:
for key in dat.keys():
    print(key)

markers_xyz_m
body_shape
mesh_contact
mesh_depth
root_xyz_shift
body_height
body_mass
images
joint_angles
bed_angle_deg


In [5]:
dat['body_shape'][0],dat['body_shape'][0].__len__()

(array([ 1.82625289,  1.93720546,  2.6573664 , -0.09655853, -2.18266708,
        -0.64559248, -1.8981005 , -1.36873223,  1.61113298, -2.45709395]),
 10)

In [22]:
dat['joint_angles'][0],dat['joint_angles'][0].__len__(),

(array([ 0.07950144,  0.0130857 , -0.43232676, -0.34981944, -0.08516278,
         0.19846299, -0.2047632 , -0.2261929 ,  0.26333876, -0.00590829,
         0.01605039,  0.00114056,  0.74215274,  0.        ,  0.        ,
         0.40648508,  0.        ,  0.        , -0.00370546,  0.01434076,
        -0.00402116,  0.05829127, -0.29055909, -0.10360811,  0.49898058,
        -0.08877306,  0.21280994, -0.0332459 ,  0.05297203, -0.00416903,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.00569665, -0.0170949 , -0.07718233,  0.19622299,
         0.25464442,  0.02110381,  0.06453974,  0.03304277,  0.19002942,
         0.00175322, -0.01219853,  0.06157679,  0.94562459, -0.21063087,
        -0.50777462,  0.09004152, -0.11962735,  0.68648436,  0.        ,
        -0.62204055,  0.        ,  0.        ,  0.11630461,  0.        ,
        -0.38814051, -0.1100192 ,  0.195815  ,  0.02491375, -0.03986225,
        -0.00154684,  0.        ,  0.        ,  0. 

In [7]:
dat['images'][0],dat['images'][0].__len__(),
# 27 * 64的图片

img = dat['images'][0].reshape(64,27)

import cv2
# 使用 cv2.imshow() 显示图像
cv2.imshow('img', img)

# 等待按键响应并关闭窗口
cv2.waitKey(0)

# 销毁所有窗口
cv2.destroyAllWindows()

In [8]:
dat['body_mass'][0],dat['body_height'][0]

(64.49814777033984, 1.8274333950651)

In [21]:
dat['markers_xyz_m'][0],dat['markers_xyz_m'][0].__len__(),


import open3d as o3d

nodes_3d = dat['markers_xyz_m'][0].reshape(24,3)

# 创建一个Open3D点云对象
pcd = o3d.geometry.PointCloud()

# 设置点云数据
pcd.points = o3d.utility.Vector3dVector(nodes_3d)

# 创建可视化窗口
o3d.visualization.draw_geometries([pcd])


In [10]:
dat['mesh_contact'][0],dat['mesh_contact'][0].__len__(), # 27*64

(array([[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]),
 64)

In [15]:

dat['mesh_depth'][0][0].__len__(),dat['mesh_depth'][0].__len__(),

(27, 64)

In [18]:
dat['root_xyz_shift'][0],dat['root_xyz_shift'][0].__len__(),

([0.7309519919560323, 1.127974717661992, 0.08024281818177006], 3)

In [20]:
dat['bed_angle_deg'][0],dat['bed_angle_deg'][0],

(0.0, 0.0)

In [23]:
import viz_synth as vs

pfile_path = r"data_BR\synth\crossed_legs\test_roll0_xl_f_lay_set1both_500.p"
subject = vs.viz_synth(pfile_path)


Exception: pyglet 2.0.9 requires Python 3.8 or newer.